# Generated by Django 5.2 on 2025-04-24 02:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('LP', 'Língua Portuguesa'), ('MAT', 'Matemática'), ('CIE', 'Ciências'), ('HIS', 'História'), ('GEO', 'Geografia'), ('ART', 'Artes'), ('EF', 'Educação Física'), ('ER', 'Ensino Religioso'), ('ING', 'Língua Inglesa'), ('LIT', 'Literatura'), ('BIO', 'Biologia'), ('FIS', 'Física'), ('QUI', 'Química'), ('FIL', 'Filosofia'), ('SOC', 'Sociologia')], max_length=3, unique=True)),
                ('nivel_ensino', models.CharField(choices=[('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio')], max_length=2)),
                ('carga_horaria', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=20)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('situacao', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('parentesco', models.CharField(choices=[('PAI', 'Pai'), ('MãE', 'Mãe'), ('AVÓ', 'Avó'), ('AVÔ', 'Avô'), ('OUTRO', 'Outro')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('escolaridade', models.CharField(choices=[('FUNDAMENTAL', 'Ensino Fundamental'), ('MEDIO', 'Ensino Médio')], max_length=20)),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=20)),
                ('serie', models.CharField(choices=[('1', '1ª Ano'), ('2', '2ª Ano'), ('3', '3ª Ano'), ('4', '4ª Ano'), ('5', '5ª Ano'), ('6', '6ª Ano'), ('7', '7ª Ano'), ('8', '8ª Ano'), ('9', '9º Ano')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('disciplina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disciplina')),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('presenca', models.BooleanField(default=True)),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
                ('disciplina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data', models.DateField(auto_now_add=True)),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
                ('avaliacao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.avaliacao')),
                ('disciplina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disciplina')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.responsavel'),
        ),
        migrations.CreateModel(
            name='Professor_Turma_Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disciplina')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.professor')),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
                ('media_geral', models.FloatField()),
                ('faltas_total', models.IntegerField()),
                ('data_geracao', models.DateField(default=django.utils.timezone.now)),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.turma')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.turma'),
        ),
        migrations.CreateModel(
            name='Turma_Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disciplina')),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.turma')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('nacionalidade', models.CharField(max_length=255)),
                ('naturalidade', models.CharField(max_length=255)),
                ('telefone', models.IntegerField(max_length=15)),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Sexo Masculino'), ('FEMININO', 'Sexo Feminino')], max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('tipo_User', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.endereco')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
