from .turmas import Turma
from .enderecos import Endereco
from .users import User
from .alunos import Aluno
from .disciplinas import Disciplina
from .avaliacoes import Avaliacao
from .notas import Nota
from .frequecias import Frequencia
from .boletins import Boletim
from .professores import Professor
from .professor_turma_disciplinas import Professor_Turma_Disciplina
from .turma_disciplina import Turma_Disciplina
