from .turmas import *
from .enderecos import *
from .users import *
from .alunos import *
from .professores import *
from .disciplinas import *
from .avaliacoes import *
from .notas import *
from .frequencias import *
from .boletins import *
from .turma_disciplinas import *
from .professor_turma_disciplinas import *